# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparcamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.URLField(default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('accessibility', models.CharField(default='', max_length=1)),
                ('district', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.CharField(blank=True, default='', max_length=200)),
                ('longitude', models.CharField(blank=True, default='', max_length=200)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=200)),
                ('contact_info', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AparcamientoSeleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('Aparcamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAparcamientos.Aparcamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField(default=0)),
                ('texto', models.TextField(default='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAparcamientos.Aparcamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField(default=0)),
                ('url', models.URLField(default='', max_length=300)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAparcamientos.Aparcamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Page_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=300)),
                ('title_page', models.CharField(default='', max_length=300)),
                ('background', models.CharField(default='', max_length=300)),
                ('size', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
