# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAparcamientos', '0002_auto_20170628_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AparcamientoSeleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=300)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aparcamiento',
            old_name='accessibilidad',
            new_name='accesibilidad',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='clasevial',
        ),
        migrations.RemoveField(
            model_name='page_user',
            name='Aparc_Selec',
        ),
        migrations.RemoveField(
            model_name='page_user',
            name='tamano_letra',
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='clasevia',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='page_user',
            name='tamaño',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aparcamientoseleccionado',
            name='Aparcamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAparcamientos.Aparcamiento'),
        ),
    ]
