# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppAparcamientos', '0003_auto_20170629_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparcamientoseleccionado',
            name='Aparcamiento',
        ),
        migrations.RenameField(
            model_name='aparcamiento',
            old_name='clasevia',
            new_name='clasevial',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='page_user',
            old_name='color_page',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='page_user',
            old_name='tamaño',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='coordenadax',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='coordenaday',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='provincia',
        ),
        migrations.AddField(
            model_name='comentario',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AparcamientoSeleccionado',
        ),
    ]
