# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAparcamientos', '0004_auto_20170629_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_user',
            name='Aparc_Selec',
            field=models.ManyToManyField(to='AppAparcamientos.Aparcamiento'),
        ),
    ]
