# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAparcamientos', '0005_page_user_aparc_selec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aparcamiento_comentado',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
